---
# roles/dns_server/vars/main.yml

bind9_base_dir: bind9
docker_compose_file_name: docker-compose.yml

named_conf_template: named.conf.j2
named_conf_file_name: named.conf

peekingface_zone_template: db.home.peekingface.eu.j2
peekingface_zone_file: home-peekingface-eu.zone

dns_forwarders: 
  - ip: 192.168.2.5

# additional debian packages
debian_packages:
  - curl
  - docker.io
  - docker-compose
  - bind9-dnsutils # not the bind9 installation, bind9 is used in the docker container