- name: "{{ inventory_hostname }} | create watchtower base directory"
  ansible.builtin.file:
    path: "{{ docker_vaultwarden_base_dir }}"
    state: directory
    owner: "{{ ansible_user }}" 
    group: "{{ ansible_user }}" 
    mode: '0755'
    recurse: yes 

- name: "{{ inventory_hostname }} | copy ansible .env file"
  ansible.builtin.copy:
    src: ".env"
    dest: "{{ docker_vaultwarden_base_dir }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: "{{ inventory_hostname }} | copy docker-compose file"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_vaultwarden_base_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

#- name: "{{ inventory_hostname }} | start vaultwarden docker container"
#  community.docker.docker_compose:
#    project_src: "{{ docker_vaultwarden_base_dir }}"
#    state: present 
