
- name: "{{ inventory_hostname }} | update apt cache"
  ansible.builtin.apt:
    update_cache: yes

- name: "{{ inventory_hostname }} | install debian packages"
  ansible.builtin.apt:
    pkg: "{{ debian_packages }}"
    state: present

- name: "{{ inventory_hostname }} | add {{ ansible_user }} to docker group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
