# playbooks/install_packages.yml

- name: "install debian packages on home servers"
  hosts: "home_servers"
  become: yes

  tasks:

    - name : "{{ inventory_hostname }} | install base and specific packages"
      ansible.builtin.apt:
        name: "{{
          base_debian_packages +
          (dns_specific_packages | default([]) if inventory_hostname in groups['dns_servers'] else []) +
          (docker_specific_packages | default([]) if inventory_hostname in groups['docker_servers'] else [])
        }}"
        state: present

    - name : "{{ inventory_hostname }} | add {{ ansible_user }} to docker group"
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: inventory_hostname not in groups['docker_servers'] # Apply only base packages to non-DNS servers
