- name: "{{ inventory_hostname }} | create immich base directory"
  ansible.builtin.file:
    path: "{{ docker_immich_base_dir }}"
    state: directory
    owner: "{{ ansible_user }}" 
    group: "{{ ansible_user }}" 
    mode: '0755'
    recurse: yes 

- name: "{{ inventory_hostname }} | create immich database directory"
  ansible.builtin.file:
    path: "{{ immich_db_data_location }}"
    state: directory
    owner: "{{ ansible_user }}" 
    group: "{{ ansible_user }}" 
    mode: '0755'
    recurse: yes 

- name: "{{ inventory_hostname }} | copy docker-compose file"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_immich_base_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: "{{ inventory_hostname }} | copy immich env file"
  ansible.builtin.template:
    src: "env.j2"
    dest: "{{ docker_immich_base_dir }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

#- name: "{{ inventory_hostname }} | start traefik docker container"
#  community.docker.docker_compose:
#    project_src: "{{ docker_immich_base_dir }}"
#    state: present 
