- name: "{{ inventory_hostname }} | create mstream base directory"
  ansible.builtin.file:
    path: "{{ docker_mstream_base_dir }}"
    state: directory
    owner: "{{ ansible_user }}" 
    group: "{{ ansible_user }}" 
    mode: '0755'
    recurse: yes 

- name: "{{ inventory_hostname }} | create mstream config directory"
  ansible.builtin.file:
    path: "{{ docker_mstream_base_dir }}/config"
    state: directory
    owner: "{{ ansible_user }}" 
    group: "{{ ansible_user }}" 
    mode: '0755'
    recurse: yes 

- name: "{{ inventory_hostname }} | copy docker-compose file"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_mstream_base_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

