all:
  vars:
    dns_domain: home.bensemer.name
    docker_base_dir: "docker"
    email: "florian@goeldenitz.org"

  children:
    dns_server:
      hosts:
        dns-01:
          ansible_user: florian
          ansible_host: 192.168.2.6

    docker_server:
      hosts:
        salamix:
          ansible_user: florian
          ansible_host: 192.168.2.201

    immich_server:
      hosts:
        immich:
          ansible_user: florian
          ansible_host: 192.168.2.202

    debian:
      children:
        dns_server:
        linux_ws: