all:
  vars:
    docker_base_dir: "docker"
    email: "florian@goeldenitz.org"

  children:
    dns_servers:
      hosts:
        dns-01:
          ansible_user: florian
          ansible_host: 192.168.2.7

    docker_servers:
      hosts:
        dockerix:
          ansible_user: florian
          ansible_host: 192.168.2.190

    home_servers:
      children:
        dns_servers: {}
        docker_servers: {}
      
#    immich_server:
#      hosts:
#        immich:
#          ansible_user: florian
#          ansible_host: 192.168.2.202
