all:
  vars:
    docker_base_dir: "docker"
    email: "florian@goeldenitz.org"

  children:
    dns_servers:
      hosts:
        dns-01:
          ansible_user: florian
          ansible_host: 192.168.2.7
          dhcp_range : "192.168.2.200 192.168.2.239"
        dns-02:
          ansible_user: florian
          ansible_host: 192.168.2.8
          dhcp_range: "192.168.2.220 192.168.2.240"

    docker_servers:
      hosts:
        dockerix:
          ansible_user: florian
          ansible_host: 192.168.2.190
        immich:
          ansible_user: florian
          ansible_host: 192.168.2.191

    home_servers:
      children:
        dns_servers: {}
        docker_servers: {}
      